### PR TITLE
Expand test matrix to macOS

### PR DESCRIPTION
**Pull request by RMeli**
Add Python 3.9, macOS and Windows to the test matrix. Enable tests on PRs.

#31

### CODE REVIEW

**Comment by RMeli** [comment]
[tempfile.NamedTemporaryFile](https://docs.python.org/3.8/library/tempfile.html#tempfile.NamedTemporaryFile)

>  That name can be retrieved from the name attribute of the returned file-like object. Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; it cannot on Windows NT or later).

**Comment by RMeli** [comment]
@f3rmion I tried to add Windows and macOS (as well as Python 3.9) to the CI. The idea was to test all platform to release a `conda` package as well. Unfortunately it seems that the following does not work on Windows:

https://github.com/AstraZeneca/kallisto/blob/17429a2f418fc3c0b91bcb5cba8a95c11db75f90/noxfile.py#L46-L57

Where you thinking to support all platforms or only Linux?

**Comment by f3rmion** [comment]
> @f3rmion I tried to add Windows and macOS (as well as Python 3.9) to the CI. The idea was to test all platform to release a `conda` package as well. Unfortunately it seems that the following does not work on Windows:
> 
> https://github.com/AstraZeneca/kallisto/blob/17429a2f418fc3c0b91bcb5cba8a95c11db75f90/noxfile.py#L46-L57
> 
> Where you thinking to support all platforms or only Linux?

Good point, I think expanding to other platforms seems reasonable.
Indeed Windows has problems with ``tempfile.NamedTemporaryFile``. A possible solution to this could be setting ``delete=False`` within the definition, which does not really help since the clean-up step has to be done manually (see [here](https://bugs.python.org/issue14243)).

**Comment by RMeli** [comment]
I agree neither is optimal. What about creating a temporary directory and simply write output files there?

>  On completion of the context or destruction of the temporary directory object the newly created temporary directory and all its contents are removed from the filesystem.

```python
with tempfile.TemporaryDirectory() as tmpdirname:
     session.run( 
         "poetry", 
         "export", 
         "--dev", 
         "--format=requirements.txt", 
         "--without-hashes", 
         f"--output={os.path.join(tmpdirname, "poetry_export.out")}", 
         external=True, 
     ) 
     install_with_constraints(session, "safety") 
     session.run("safety", "check", f"--file={os.path.join(tmpdirname, "safety_check.out")}", "--full-report") 
```

**Comment by RMeli** [comment]
It seems to work, but now all the tests using `tempfile.NamedTemporaryFile()` need to change as well.

This relates to #31 ; since you are testing via the CLI instead of the functions directly, most tests need files.

**Comment by f3rmion** [comment]
See latest changes in #31

**Comment by RMeli** [comment]
There are problems with [pytype](https://github.com/google/pytype), which does not seem to support Windows... =(

> Windows is currently not supported unless you use WSL.

I can see two solutions here:
* Remove `pytype` from the CI until Windows is supported
* Drop support for Windows

**Comment by RMeli** [comment]
> I can see two solutions here:
>
> * Remove pytype from the CI until Windows is supported
> * Drop support for Windows


There are other problems with Windows, especially with the CLI. Unless you have a Windows machine to test and fix things locally (I don't), I will have to suggest the second option unfortunately.

**Comment by f3rmion** [comment]
> > I can see two solutions here:
> > 
> > * Remove pytype from the CI until Windows is supported
> > * Drop support for Windows
> 
> There are other problems with Windows, especially with the CLI. Unless you have a Windows machine to test and fix things locally (I don't), I will have to suggest the second option unfortunately.

Hi @RMeli, thanks for your effort! As the support for Windows would probably take more effort, I also think we should do without it for the time being (especially as I don't have a local machine available either).

**Comment by f3rmion** [comment]
Could you please squash and sign the PR? I think then we are ready to merge.

**Comment by RMeli** [comment]
You should be able to squash when merging. What do you mean by signing the PR?

**Comment by f3rmion** [comment]
> You should be able to squash when merging. What do you mean by signing the PR?

See the contributing [guidelines](https://github.com/AstraZeneca/kallisto/blob/master/CONTRIBUTING.md) (Sign Your Work).

It is a message at the end of your commit, an example would be:
```bash
Signed-off-by: Joe Smith <joe.smith@example.com>
```

Afterwards, I add you to the contributors list.

**Comment by RMeli** [comment]
Can you add the following when squash-merging? 

> Signed-off-by: Rocco Meli <rocco.meli@biodtp.ox.ac.uk>

I think it is the easiest option.

**Pull request merged**
