### PR TITLE
Update methods.py

### PR DESCRIPTION
**Pull request by albernsrya**
**return statement causes the control flow to be disrupted**
making the else / elif block here unnecessary. This doesn't mean you can not use it, but it is recommended to refactor this for a better readability.

### CODE REVIEW

**Review by f3rmion — COMMENTED** [review]
The indentation is incorrect in your change. Please use ``nox`` with the implemented sessions to check your code, accordingly. When this has been done, I'll check the contribution using our CI.

**Comment by albernsrya** [comment]
okay thank you for your feedback

**Review by f3rmion — COMMENTED** [review]
Also this contribution is not correctly intended. Please check your code.

**Comment by albernsrya** [comment]
thanks for you feedback, i will check again

**Comment by f3rmion** [comment]
@albernsrya Any updates on this? Otherwise, I'll close this PR.

**Pull request closed without merging**
